/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_firebase;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Marvin Batres
 */
public class Registro_Herramienta extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Herramienta
     */
    public Registro_Herramienta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTablaAsistenteCasa = new javax.swing.JTable();
        btRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGarantia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTipoDispositivo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProtComunicacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCompAsistente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPantalla = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEnt_Sal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtInalambrico = new javax.swing.JTextField();
        txtRangoConexion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHub = new javax.swing.JTextField();
        btActualizar = new javax.swing.JButton();
        btBusqueda = new javax.swing.JButton();
        btLimpieza = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTablaAsistenteCasa1 = new javax.swing.JTable();
        btRegistrar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtStock1 = new javax.swing.JTextField();
        txtMarca1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtModelo1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtGarantia1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTipoDispositivo1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtProtComunicacion1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtCompAsistente1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPantalla1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtEnt_Sal1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtInalambrico1 = new javax.swing.JTextField();
        txtRangoConexion1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtHub1 = new javax.swing.JTextField();
        btActualizar1 = new javax.swing.JButton();
        btBusqueda1 = new javax.swing.JButton();
        btLimpieza1 = new javax.swing.JButton();
        btEliminar1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtNOmbre = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPRecio = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtSTock = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtMArca = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtMOdelo = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtGArantia = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtTIpherramienta = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtFuente = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtVoltaje = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtFbateria = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtEstuche = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtAplic = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtCanpiezas = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBusquedaID = new javax.swing.JButton();
        btnLimpieza = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresarMenu = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTablaAsistenteCasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTablaAsistenteCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaAsistenteCasaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbTablaAsistenteCasa);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 980, 195));

        btRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 495, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 207, 37, 30));
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 214, 103, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 243, 86, 30));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 103, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Precio:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 279, -1, 30));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 286, 103, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Stock:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 315, -1, 30));
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 322, 103, -1));
        jPanel2.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 358, 103, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Marca:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 351, 61, 30));
        jPanel2.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 394, 103, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Modelo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 387, 97, 30));
        jPanel2.add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 430, 109, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Garantia:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 423, 97, 30));
        jPanel2.add(txtTipoDispositivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 214, 113, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("TipoDisp:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Prot. Comunicación:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 246, -1, -1));
        jPanel2.add(txtProtComunicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 250, 99, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Comp. Asistente:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 282, -1, -1));
        jPanel2.add(txtCompAsistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 286, 117, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Tiene Pantalla: b");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 318, 153, -1));
        jPanel2.add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 322, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tipo de E/S:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 354, 141, -1));
        jPanel2.add(txtEnt_Sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 358, 104, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("esInalambrico: b");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 390, 153, -1));
        jPanel2.add(txtInalambrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 394, 120, -1));
        jPanel2.add(txtRangoConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 430, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Rango Conexión:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 426, 153, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Hub: b");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 60, 30));
        jPanel2.add(txtHub, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 466, 109, -1));

        btActualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 495, -1, -1));

        btBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btBusqueda.setText("BusquedaID");
        btBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(btBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 495, -1, -1));

        btLimpieza.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btLimpieza.setText("Limpiar");
        btLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiezaActionPerformed(evt);
            }
        });
        jPanel2.add(btLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 495, -1, -1));

        btEliminar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 495, -1, -1));

        jButton6.setText("Regresar menu principal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 530, 191, 31));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTablaAsistenteCasa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTablaAsistenteCasa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaAsistenteCasa1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbTablaAsistenteCasa1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 980, 195));

        btRegistrar1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btRegistrar1.setText("Registrar");
        btRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 495, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("ID:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 207, 37, 30));
        jPanel3.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 214, 103, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Nombre:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 243, 86, 30));
        jPanel3.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 103, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Precio:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 279, -1, 30));
        jPanel3.add(txtPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 286, 103, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Stock:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 315, -1, 30));
        jPanel3.add(txtStock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 322, 103, -1));
        jPanel3.add(txtMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 358, 103, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Marca:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 351, 61, 30));
        jPanel3.add(txtModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 394, 103, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Modelo:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 387, 97, 30));
        jPanel3.add(txtGarantia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 430, 109, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Garantia:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 423, 97, 30));
        jPanel3.add(txtTipoDispositivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 214, 113, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("TipoDisp:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Prot. Comunicación:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 246, -1, -1));
        jPanel3.add(txtProtComunicacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 250, 99, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Comp. Asistente:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 282, -1, -1));
        jPanel3.add(txtCompAsistente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 286, 117, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Tiene Pantalla: b");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 318, 153, -1));
        jPanel3.add(txtPantalla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 322, 120, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Tipo de E/S:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 354, 141, -1));
        jPanel3.add(txtEnt_Sal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 358, 104, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("esInalambrico: b");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 390, 153, -1));
        jPanel3.add(txtInalambrico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 394, 120, -1));
        jPanel3.add(txtRangoConexion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 430, 120, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Rango Conexión:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 426, 153, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Hub: b");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 60, 30));
        jPanel3.add(txtHub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 466, 109, -1));

        btActualizar1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btActualizar1.setText("Actualizar");
        btActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 495, -1, -1));

        btBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btBusqueda1.setText("BusquedaID");
        btBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBusqueda1ActionPerformed(evt);
            }
        });
        jPanel3.add(btBusqueda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 495, -1, -1));

        btLimpieza1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btLimpieza1.setText("Limpiar");
        btLimpieza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpieza1ActionPerformed(evt);
            }
        });
        jPanel3.add(btLimpieza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 495, -1, -1));

        btEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btEliminar1.setText("Eliminar");
        btEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 495, -1, -1));

        jButton7.setText("Regresar menu principal");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 530, 191, 31));

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 809, 158));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel31.setText("ID:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 170, 33, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 172, 103, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setText("Nombre:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 200, 68, -1));
        jPanel1.add(txtNOmbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 202, 103, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel33.setText("Precio:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 230, 68, -1));
        jPanel1.add(txtPRecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 232, 103, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel34.setText("Stock:");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 266, 60, -1));
        jPanel1.add(txtSTock, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 268, 103, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel35.setText("Marca:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 302, 68, -1));
        jPanel1.add(txtMArca, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 304, 103, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel36.setText("Modelo:");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 170, 72, -1));
        jPanel1.add(txtMOdelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 172, 146, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel37.setText("Garantía:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 200, 72, -1));
        jPanel1.add(txtGArantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 202, 54, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel38.setText("Tip. Her:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 230, 72, -1));
        jPanel1.add(txtTIpherramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 232, 146, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel39.setText("Fuente Energia:");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 266, -1, -1));
        jPanel1.add(txtFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 268, 103, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel40.setText("Voltaje:");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 302, 73, -1));
        jPanel1.add(txtVoltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 304, 115, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel41.setText("Fuente Batería:");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 170, 125, -1));

        txtFbateria.setText("boolean");
        jPanel1.add(txtFbateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 172, 103, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel42.setText("Incluye estuche:");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 200, 125, -1));

        txtEstuche.setText("boolean");
        jPanel1.add(txtEstuche, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 202, 103, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel43.setText("Material:");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 230, -1, -1));
        jPanel1.add(txtMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 232, 103, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel44.setText("Aplicación:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 266, -1, -1));
        jPanel1.add(txtAplic, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 268, 179, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel45.setText("Cant. Piezas:");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 302, 104, -1));
        jPanel1.add(txtCanpiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 304, 164, -1));

        btnRegistar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistar.setText("Registrar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 362, -1, 49));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 362, -1, 49));

        btnBusquedaID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBusquedaID.setText("BusquedaID");
        jPanel1.add(btnBusquedaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 362, -1, 49));

        btnLimpieza.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpieza.setText("Limpieza");
        jPanel1.add(btnLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 362, -1, 49));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 362, -1, 49));

        btnRegresarMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresarMenu.setText("Regresar al menu");
        btnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 440, 239, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTablaAsistenteCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaAsistenteCasaMouseClicked

    }//GEN-LAST:event_tbTablaAsistenteCasaMouseClicked

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed

    }//GEN-LAST:event_btRegistrarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed

    }//GEN-LAST:event_btActualizarActionPerformed

    private void btBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusquedaActionPerformed

    }//GEN-LAST:event_btBusquedaActionPerformed

    private void btLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiezaActionPerformed

    }//GEN-LAST:event_btLimpiezaActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed

    }//GEN-LAST:event_btEliminarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu_Principal principal = new Menu_Principal();

        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tbTablaAsistenteCasa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaAsistenteCasa1MouseClicked


    }//GEN-LAST:event_tbTablaAsistenteCasa1MouseClicked

    private void btRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrar1ActionPerformed

    }//GEN-LAST:event_btRegistrar1ActionPerformed

    private void btActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizar1ActionPerformed

    }//GEN-LAST:event_btActualizar1ActionPerformed

    private void btBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusqueda1ActionPerformed

    }//GEN-LAST:event_btBusqueda1ActionPerformed

    private void btLimpieza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpieza1ActionPerformed

    }//GEN-LAST:event_btLimpieza1ActionPerformed

    private void btEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminar1ActionPerformed

    }//GEN-LAST:event_btEliminar1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        guardar();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuActionPerformed
        Menu_Principal principal = new Menu_Principal();

        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Herramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Herramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Herramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Herramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Herramienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btActualizar1;
    private javax.swing.JButton btBusqueda;
    private javax.swing.JButton btBusqueda1;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btEliminar1;
    private javax.swing.JButton btLimpieza;
    private javax.swing.JButton btLimpieza1;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btRegistrar1;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBusquedaID;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpieza;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbTablaAsistenteCasa;
    private javax.swing.JTable tbTablaAsistenteCasa1;
    private javax.swing.JTextField txtAplic;
    private javax.swing.JTextField txtCanpiezas;
    private javax.swing.JTextField txtCompAsistente;
    private javax.swing.JTextField txtCompAsistente1;
    private javax.swing.JTextField txtEnt_Sal;
    private javax.swing.JTextField txtEnt_Sal1;
    private javax.swing.JTextField txtEstuche;
    private javax.swing.JTextField txtFbateria;
    private javax.swing.JTextField txtFuente;
    private javax.swing.JTextField txtGArantia;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtGarantia1;
    private javax.swing.JTextField txtHub;
    private javax.swing.JTextField txtHub1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInalambrico;
    private javax.swing.JTextField txtInalambrico1;
    private javax.swing.JTextField txtMArca;
    private javax.swing.JTextField txtMOdelo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMarca1;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtModelo1;
    private javax.swing.JTextField txtNOmbre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtPRecio;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JTextField txtPantalla1;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtProtComunicacion;
    private javax.swing.JTextField txtProtComunicacion1;
    private javax.swing.JTextField txtRangoConexion;
    private javax.swing.JTextField txtRangoConexion1;
    private javax.swing.JTextField txtSTock;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStock1;
    private javax.swing.JTextField txtTIpherramienta;
    private javax.swing.JTextField txtTipoDispositivo;
    private javax.swing.JTextField txtTipoDispositivo1;
    private javax.swing.JTextField txtVoltaje;
    // End of variables declaration//GEN-END:variables

    private HerramientaElectronica crearCamposherramienta() {
        return new HerramientaElectronica(
                Integer.parseInt(txtId.getText()),
                txtNOmbre.getText(),
                Double.parseDouble(txtPRecio.getText()),
                Integer.parseInt(txtSTock.getText()),
                txtMArca.getText(),
                txtMOdelo.getText(),
                Double.parseDouble(txtGArantia.getText()),
                txtTIpherramienta.getText(),
                txtFuente.getText(),
                Double.parseDouble(txtVoltaje.getText()),
                Boolean.parseBoolean(txtFbateria.getText()),
                Boolean.parseBoolean(txtEstuche.getText()),
                txtMaterial.getText(),
                txtAplic.getText(),
                Integer.parseInt(txtCanpiezas.getText())
        );

    }

    private Map<String, Object> crearMapeoDatosHerramienta(HerramientaElectronica herramienta) {
        Map<String, Object> datos = new HashMap();
        datos.put("Nombre", herramienta.getNombre());
        datos.put("Precio", herramienta.getPrecio());
        datos.put("Stock", herramienta.getStock());
        datos.put("Marca", herramienta.getMarca());
        datos.put("Modelo", herramienta.getModelo());
        datos.put("Garantia", herramienta.getGarantia());
        datos.put("tipoHerramienta", herramienta.getTipoHerramienta());
        datos.put("tipoFuenteEnergia", herramienta.getTipoFuenteEnergia());
        datos.put("voltaje", herramienta.getVoltaje());
        datos.put("fuenteDeBateria", herramienta.isFuenteDeBateria());
        datos.put("IncluyeEstuche", herramienta.isIncluyeEstuche());
        datos.put("Material", herramienta.getMaterial());
        datos.put("Aplicacion", herramienta.getAplicacion());
        datos.put("CantidadPiezas", herramienta.getCantidadPiezas());

        return datos;
    }

    private void guardar() {
        HerramientaElectronica herramienta = crearCamposherramienta();

        try {
            Map<String, Object> datos = crearMapeoDatosHerramienta(herramienta);
            Crud_HerramientaElectronica.guardarHer_Elect("HerramientaElectronica", String.valueOf(herramienta.getId()), datos);
            JOptionPane.showMessageDialog(null, "Guardado con éxito");

       } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al guardar los datos");

        }

    }
}
