/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_firebase;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author Marvin Batres
 */
public class Registro_computadora extends javax.swing.JFrame {

    /**
     * Creates new form Registro_computadora
     */
    public Registro_computadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        Crud_computadora.cargarTablaComputadora(tbTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabla = new javax.swing.JTable();
        btLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtProcesador = new javax.swing.JTextField();
        txtTamGb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTarjG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTipoComputadora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtConexion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btBusqueda = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 840, 180));

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 90, 40));

        jLabel1.setText("Procesador:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, 120, 31));

        txtProcesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcesadorActionPerformed(evt);
            }
        });
        jPanel1.add(txtProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 150, -1));

        txtTamGb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamGbActionPerformed(evt);
            }
        });
        jPanel1.add(txtTamGb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 150, -1));

        jLabel2.setText("Tamaño de GB:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 221, 120, 31));

        txtTarjG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarjGActionPerformed(evt);
            }
        });
        jPanel1.add(txtTarjG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 150, -1));

        jLabel3.setText("Tarjeta Grafica:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 258, 120, 31));

        txtTipoComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoComputadoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtTipoComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 150, -1));

        jLabel4.setText("Tipo de Computadora:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 295, 120, 31));

        txtConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConexionActionPerformed(evt);
            }
        });
        jPanel1.add(txtConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 150, -1));

        jLabel5.setText("Tipo de conexión:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 332, 120, 31));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 70, -1));

        jLabel6.setText("Id:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 40, 20));

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 80, -1));

        jLabel7.setText("Precio:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 50, 20));

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 90, -1));

        jLabel8.setText("Stocks:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 50, 20));

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 90, -1));

        jLabel9.setText("Marca:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 50, 20));

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, -1));

        jLabel10.setText("Modelo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 53, 20));

        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 70, -1));

        jLabel11.setText("Descuento:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 70, 20));

        jLabel12.setText("Nombre:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 50, 20));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 140, -1));

        jButton1.setText("Regresar al Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, 30));

        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, 40));

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 90, 40));

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, 40));

        btBusqueda.setText("Busqueda ID");
        btBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(btBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        clearForm();
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void txtProcesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcesadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcesadorActionPerformed

    private void txtTamGbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamGbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamGbActionPerformed

    private void txtTarjGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarjGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjGActionPerformed

    private void txtTipoComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoComputadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoComputadoraActionPerformed

    private void txtConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConexionActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu_Principal principal = new Menu_Principal();

        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        guardar();
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusquedaActionPerformed
        BusquedaID();
    }//GEN-LAST:event_btBusquedaActionPerformed

    private void tbTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaMouseClicked
        int seleccion = tbTabla.getSelectedRow();
        txtProcesador.setText(tbTabla.getValueAt(seleccion, 0) + "");
        txtTamGb.setText(tbTabla.getValueAt(seleccion, 1) + "");
        txtTarjG.setText(tbTabla.getValueAt(seleccion, 2) + "");
        txtTipoComputadora.setText(tbTabla.getValueAt(seleccion, 3) + "");
        txtConexion.setText(tbTabla.getValueAt(seleccion, 4) + "");
        txtID.setText(tbTabla.getValueAt(seleccion, 5) + "");
        txtNombre.setText(tbTabla.getValueAt(seleccion, 6) + "");
        txtPrecio.setText(tbTabla.getValueAt(seleccion, 7) + "");
        txtStock.setText(tbTabla.getValueAt(seleccion, 8) + "");
        txtMarca.setText(tbTabla.getValueAt(seleccion, 9) + "");
        txtModelo.setText(tbTabla.getValueAt(seleccion, 10) + "");
        txtDescuento.setText(tbTabla.getValueAt(seleccion, 11) + "");

    }//GEN-LAST:event_tbTablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_computadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_computadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_computadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_computadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_computadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btBusqueda;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTabla;
    private javax.swing.JTextField txtConexion;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProcesador;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTamGb;
    private javax.swing.JTextField txtTarjG;
    private javax.swing.JTextField txtTipoComputadora;
    // End of variables declaration//GEN-END:variables

    //Patron FACADE
    private Computadora crearCamposComputadora() {

        return new Computadora(
                txtProcesador.getText(),
                Integer.parseInt(txtTamGb.getText()),
                txtTarjG.getText(),
                txtTipoComputadora.getText(),
                txtConexion.getText(),
                Integer.parseInt(txtID.getText()),
                txtNombre.getText(),
                Double.parseDouble(txtPrecio.getText()),
                Integer.parseInt(txtStock.getText()),
                txtMarca.getText(),
                txtModelo.getText(),
                Double.parseDouble(txtDescuento.getText())
        );

    }

    //Metodo para el mapeo
    private Map<String, Object> crearMapeoDatosCompu(Computadora compu) {
        Map<String, Object> datos = new HashMap();
        datos.put("procesador", compu.getProcesador());
        datos.put("tamañoGb", compu.getAlmacenamientoGB());
        datos.put("TarjetaGr", compu.getTarjGrafica());
        datos.put("TipoComputadora", compu.getTipoComputadora());
        datos.put("EstadoConexion", compu.getEstConexion());
        datos.put("Nombre", compu.getNombre());
        datos.put("Precio", compu.getPrecio());
        datos.put("Stock", compu.getStock());
        datos.put("Marca", compu.getMarca());
        datos.put("Modelo", compu.getModelo());
        datos.put("Garantia", compu.getGarantia());

        return datos;
    }

    private void guardar() {
        Computadora compu = crearCamposComputadora();
        MostrarInterfaces(compu); //Mostrar interfaces

        try {

            Map<String, Object> datos = crearMapeoDatosCompu(compu);
            Crud_computadora.guardarComputadora("Computadora", String.valueOf(compu.getId()), datos);
            JOptionPane.showMessageDialog(null, "Guardado con éxito");
            clearForm();

        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al guardar");

        } finally {

            Crud_computadora.cargarTablaComputadora(tbTabla);

        }
    }

    private void actualizar() {
        Computadora compu = crearCamposComputadora();
        MostrarInterfaces(compu);//Mostrar interfaces

        try {
            Map<String, Object> datos = crearMapeoDatosCompu(compu);
            Crud_computadora.actualizarComputadora("Computadora", String.valueOf(compu.getId()), datos);
            JOptionPane.showMessageDialog(null, "Actualizacioón de datos con éxito");
            clearForm();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al actualizar");

        } finally {

            Crud_computadora.cargarTablaComputadora(tbTabla);

        }

    }

    private void eliminar() {
        String idDoc = txtID.getText();

        try {
            Crud_computadora.eliminarComputadora("Computadora", idDoc);
            JOptionPane.showMessageDialog(null, "Eliminación de los datos con éxito");
            clearForm();

        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al eliminar los datos");

        } finally {

            Crud_computadora.cargarTablaComputadora(tbTabla);

        }

    }

    private void clearForm() {
        txtProcesador.setText("");
        txtTamGb.setText("");
        txtTarjG.setText("");
        txtTipoComputadora.setText("");
        txtConexion.setText("");
        txtID.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtDescuento.setText("");
                    Crud_computadora.cargarTablaComputadora(tbTabla);

    }

    private void MostrarInterfaces(Computadora compu) {

        System.out.println("*** Conectable ***");
        compu.EstadoConexion("Probando conexión");
        boolean conectado = compu.Conectar();
        System.out.println("Conectado: " + conectado);
        boolean desconectado = compu.Desconectar();
        System.out.println("Desconectado: " + desconectado);

        // **INTERFACE GarantiaExtendida - Probando todos sus métodos**
        System.out.println("**** Impresion GarantiaExtendida ****");
        boolean elegible = compu.GarantiaElegibleExtendida();
        System.out.println("Elegible para garantía: " + elegible);

        if (elegible) {
            double costo = compu.calcularCostoGarantia(compu.getPrecio());
            System.out.println("Costo garantía Q" + compu.getCostoGarantiaFormato());
        }

        // **MÉTODOS DE Producto (clase padre)**
        System.out.println("****Producto****");
        System.out.println("Precio con IVA: Q" + compu.IvaFOrmateado());
        System.out.println("Categoría: " + compu.getTipoCategoria());

    }

    private void BusquedaID() {

        try {
            String idBusqueda = txtID.getText().trim();

            if (idBusqueda.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese un ID de Busqueda en el campo 'ID'");
                return;
            }

            Computadora compuBuscada = Crud_computadora.buscarComputadoraID(idBusqueda);

            if (compuBuscada != null) {
                llenarCamposConComputadora(compuBuscada);
                JOptionPane.showMessageDialog(null, "Computadora encontrada con Id: " + idBusqueda);
                mostrarEnTabla(compuBuscada);
                
            } else {
                JOptionPane.showMessageDialog(null, "Computadora No encontrada ");
                clearForm();
            }

        } catch (Exception e) {
            System.err.println("Error al buscar computadora: " + e.getMessage());
            
        }

    }

    private void llenarCamposConComputadora(Computadora compu) {
        txtProcesador.setText(compu.getProcesador());
        txtTamGb.setText(String.valueOf(compu.getAlmacenamientoGB()));
        txtTarjG.setText(compu.getTarjGrafica());
        txtTipoComputadora.setText(compu.getTipoComputadora());
        txtConexion.setText(compu.getEstConexion());
        // txtID.setText(String.valueOf(compu.getId())); // Ya está lleno
        txtNombre.setText(compu.getNombre());
        txtPrecio.setText(String.valueOf(compu.getPrecio()));
        txtStock.setText(String.valueOf(compu.getStock()));
        txtMarca.setText(compu.getMarca());
        txtModelo.setText(compu.getModelo());
        txtDescuento.setText(String.valueOf(compu.getGarantia()));
    }

    
    private void mostrarEnTabla(Computadora compu) {
    // Obtener el modelo de la tabla
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tbTabla.getModel();
    
    // Limpiar la tabla
    modelo.setRowCount(0);
    
    // Agregar la fila con los datos de la computadora
    Object[] fila = {
        compu.getProcesador(),
        compu.getAlmacenamientoGB(),
        compu.getTarjGrafica(),
        compu.getTipoComputadora(),
        compu.getEstConexion(),
        compu.getId(),
        compu.getNombre(),
        compu.getPrecio(),
        compu.getStock(),
        compu.getMarca(),
        compu.getModelo(),
        compu.getGarantia()
    };
    
    modelo.addRow(fila);
}
    
    
}
