package com.mycompany.proyecto_firebase;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
/*
 * Interfaz gráfica para el registro y gestión de herramientas electrónicas
 * Proporciona funcionalidades CRUD (Crear, Leer, Actualizar, Eliminar) 
 * para herramientas electrónicas con integración a base de datos Firebase
 *
*/

public class Registro_Herramienta extends javax.swing.JFrame {

    /**    
     * Constructor principal que inicializa la interfaz y configura componentes
    */
    public Registro_Herramienta() {
        initComponents();
        this.setLocationRelativeTo(null);
        Crud_HerramientaElectronica.cargarTablaHerramienta(tbTablaHerramienta);

        configurarComboBox();
        configurarComboBoxBooleano();

    }

    /**
     * Configura los valores de los ComboBoxs para tipos de herramientas disponibles
     */    
   
    private void configurarComboBox() {

        jComboBox1.removeAllItems();

        jComboBox1.addItem("desarmador de precisión");
        jComboBox1.addItem("pinza de corte");
        jComboBox1.addItem("sopladora");
        jComboBox1.addItem("multímetro");
        jComboBox1.addItem("osciloscopio");
        jComboBox1.addItem("fuente de poder");
        jComboBox1.addItem("kit de desarmadores");
        jComboBox1.addItem("soldador básico");

        jComboBox1.setSelectedIndex(0);

    }
    
    /**
     * Configura los ComboBox para campos booleanos (true/false)
     */

    private void configurarComboBoxBooleano() { //--------------------Metodo implemetado
        ListBotonFuenteBateria.removeAllItems();
        ListBotonFuenteBateria.addItem("true");
        ListBotonFuenteBateria.addItem("false");
        ListBotonFuenteBateria.setSelectedItem("false");

        btEstuche.removeAllItems();
        btEstuche.addItem("true");
        btEstuche.addItem("false");

        btEstuche.setSelectedItem("false");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTablaHerramienta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIngreso = new javax.swing.JTextField();
        txtNOmbre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPRecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSTock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMOdelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGArantia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVoltaje = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFbateria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMArca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEstuche = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAplic = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCanpiezas = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpieza = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtFuente = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ListBotonFuenteBateria = new javax.swing.JComboBox<>();
        btEstuche = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTablaHerramienta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTablaHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaHerramientaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTablaHerramienta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 1200, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 185, 31, -1));

        txtIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 189, 141, -1));
        jPanel1.add(txtNOmbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 221, 108, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 217, -1, -1));
        jPanel1.add(txtPRecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 253, 141, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Precio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 249, 68, -1));
        jPanel1.add(txtSTock, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 291, 141, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Stock:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 287, -1, -1));

        txtMOdelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMOdeloActionPerformed(evt);
            }
        });
        jPanel1.add(txtMOdelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 189, 141, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Registro Herramientas Electronicas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 30));
        jPanel1.add(txtGArantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 221, 141, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Garantía:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 217, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Tip. Herramienta:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 249, -1, -1));
        jPanel1.add(txtVoltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 291, 99, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Voltaje:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 287, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Fuente de Bateria: b");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 319, 180, -1));
        jPanel1.add(txtFbateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Marca:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 319, 74, -1));
        jPanel1.add(txtMArca, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 323, 141, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText(" Incluye Estuche: b");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 185, -1, -1));
        jPanel1.add(txtEstuche, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 20, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Material:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 217, -1, -1));
        jPanel1.add(txtMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 221, 168, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Aplicación:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 287, -1, -1));
        jPanel1.add(txtAplic, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 291, 320, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Cantida de Piezas:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 319, -1, -1));

        txtCanpiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanpiezasActionPerformed(evt);
            }
        });
        jPanel1.add(txtCanpiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 323, 100, -1));

        btnRegistar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistar.setText("Registrar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 363, 112, 63));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 363, -1, 63));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setText("BusquedaID");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 363, -1, 63));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 363, 112, 63));

        btnLimpieza.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpieza.setText("Limpieza");
        btnLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiezaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 363, 118, 63));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setText("Regresar al Menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 213, 24));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Tipo Fuente:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 249, 114, -1));
        jPanel1.add(txtFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 253, 128, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "desarmador de precisión", "pinza de corte", "sopladora", "multímetro", "osciloscopio", "fuente de poder", "kit de desarmadores", "soldador básico", "predeterminado" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 170, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Modelo:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 185, -1, -1));

        ListBotonFuenteBateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false", " " }));
        jPanel1.add(ListBotonFuenteBateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, 30));

        btEstuche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));
        btEstuche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstucheActionPerformed(evt);
            }
        });
        jPanel1.add(btEstuche, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMOdeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMOdeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMOdeloActionPerformed

    private void txtCanpiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanpiezasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCanpiezasActionPerformed

    private void btnLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiezaActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLimpiezaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu_Principal principal = new Menu_Principal();

        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        guardar();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void txtIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        busquedaID();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tbTablaHerramientaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaHerramientaMouseClicked
        int seleccion = tbTablaHerramienta.getSelectedRow();

        if (seleccion >= 0) {

            txtIngreso.setText(tbTablaHerramienta.getValueAt(seleccion, 0) + "");
            txtNOmbre.setText(tbTablaHerramienta.getValueAt(seleccion, 1) + "");
            txtPRecio.setText(tbTablaHerramienta.getValueAt(seleccion, 2) + "");
            txtSTock.setText(tbTablaHerramienta.getValueAt(seleccion, 3) + "");
            txtMArca.setText(tbTablaHerramienta.getValueAt(seleccion, 4) + "");
            txtMOdelo.setText(tbTablaHerramienta.getValueAt(seleccion, 5) + "");
            txtGArantia.setText(tbTablaHerramienta.getValueAt(seleccion, 6) + "");
            jComboBox1.setSelectedItem(tbTablaHerramienta.getValueAt(seleccion, 7) + ""); // tipoHerramienta
            txtFuente.setText(tbTablaHerramienta.getValueAt(seleccion, 8) + "");
            txtVoltaje.setText(tbTablaHerramienta.getValueAt(seleccion, 9) + "");
            //Cambios 
            ListBotonFuenteBateria.setSelectedItem(tbTablaHerramienta.getValueAt(seleccion, 10) + "");
            btEstuche.setSelectedItem(tbTablaHerramienta.getValueAt(seleccion, 11) + "");

            txtMaterial.setText(tbTablaHerramienta.getValueAt(seleccion, 12) + "");//
            txtAplic.setText(tbTablaHerramienta.getValueAt(seleccion, 13) + "");//
            txtCanpiezas.setText(tbTablaHerramienta.getValueAt(seleccion, 14) + "");

        } else {
            JOptionPane.showMessageDialog(this, "Error: La tabla No tiene todas las columnas esperadas del registro.");
        }


    }//GEN-LAST:event_tbTablaHerramientaMouseClicked

    private void btEstucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstucheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEstucheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Herramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Herramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Herramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Herramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Herramienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListBotonFuenteBateria;
    private javax.swing.JComboBox<String> btEstuche;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpieza;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTablaHerramienta;
    private javax.swing.JTextField txtAplic;
    private javax.swing.JTextField txtCanpiezas;
    private javax.swing.JTextField txtEstuche;
    private javax.swing.JTextField txtFbateria;
    private javax.swing.JTextField txtFuente;
    private javax.swing.JTextField txtGArantia;
    private javax.swing.JTextField txtIngreso;
    private javax.swing.JTextField txtMArca;
    private javax.swing.JTextField txtMOdelo;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtNOmbre;
    private javax.swing.JTextField txtPRecio;
    private javax.swing.JTextField txtSTock;
    private javax.swing.JTextField txtVoltaje;
    // End of variables declaration//GEN-END:variables

     /**
     * Valida que los campos obligatorios del formulario estén completos
     * @return true si todos los campos obligatorios son válidos, false en caso contrario
     */
    private boolean validarCampos() {
        if (txtIngreso.getText().trim().isEmpty()
                || txtNOmbre.getText().trim().isEmpty()
                || txtPRecio.getText().trim().isEmpty()
                || txtSTock.getText().trim().isEmpty()
                || jComboBox1.getSelectedItem().toString().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor, Debe ingresar todos los campos obligatorios.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            Double.parseDouble(txtPRecio.getText().trim());
            Integer.parseInt(txtSTock.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio y la cantidad deben ser valores numéricos.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    /**
     * Crea un objeto HerramientaElectronica a partir de los datos del formulario
     * @return retorna un Objeto HerramientaElectronica con los datos del formulario
     */
    
    private HerramientaElectronica crearCamposherramienta() {

        try {
            return new HerramientaElectronica(
                    Integer.parseInt(txtIngreso.getText().trim()),
                    txtNOmbre.getText(),
                    Double.parseDouble(txtPRecio.getText().trim()),
                    Integer.parseInt(txtSTock.getText().trim()),
                    txtMArca.getText().trim(),
                    txtMOdelo.getText().trim(),
                    Double.parseDouble(txtGArantia.getText().trim()),
                    jComboBox1.getSelectedItem().toString().trim(),//

                    txtFuente.getText().trim(),
                    Double.parseDouble(txtVoltaje.getText().trim()),
                    //Cambios implemetados
                    Boolean.parseBoolean(ListBotonFuenteBateria.getSelectedItem().toString()), // ,txtFbateria.getText().trim()),
                    Boolean.parseBoolean(btEstuche.getSelectedItem().toString()), //,txtEstuche.getText().trim()),

                    txtMaterial.getText().trim(),
                    txtAplic.getText().trim(),
                    Integer.parseInt(txtCanpiezas.getText().trim())
            );

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio y la cantidad deben ser valores numéricos.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
            return null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear herramienta: " + e.getMessage());
            return null;

        }
    }

    private Map<String, Object> crearMapeoDatosHerramienta(HerramientaElectronica herramienta) {
        Map<String, Object> datos = new HashMap();
        datos.put("Nombre", herramienta.getNombre());
        datos.put("Precio", herramienta.getPrecio());
        datos.put("Stock", herramienta.getStock());
        datos.put("Marca", herramienta.getMarca());
        datos.put("Modelo", herramienta.getModelo());
        datos.put("Garantia", herramienta.getGarantia());
        datos.put("tipoHerramienta", herramienta.getTipoHerramienta());
        datos.put("tipoFuenteEnergia", herramienta.getTipoFuenteEnergia());
        datos.put("voltaje", herramienta.getVoltaje());
        datos.put("fuenteDeBateria", herramienta.isFuenteDeBateria());
        datos.put("IncluyeEstuche", herramienta.isIncluyeEstuche());
        datos.put("Material", herramienta.getMaterial());
        datos.put("Aplicacion", herramienta.getAplicacion());
        datos.put("CantidadPiezas", herramienta.getCantidadPiezas());

        return datos;
    }
    
    /**
     * Guarda un objeto de una nueva herramienta electrónica en la base de datos
     * Realiza validación de campos antes del guardado
     */
    
    private void guardar() {

        if (!validarCampos()) {
            return;
        }
        HerramientaElectronica herramienta = crearCamposherramienta();

        if (herramienta == null) {
            return;
        }
        try {

            Map<String, Object> datos = crearMapeoDatosHerramienta(herramienta);

            Crud_HerramientaElectronica.guardarHer_Elect("HerramientaElectronica", String.valueOf(herramienta.getId()), datos);
            JOptionPane.showMessageDialog(null, "Guardado con éxito");
            clearForm();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al guardar los datos de Herramientas");

        } finally {
            Crud_HerramientaElectronica.cargarTablaHerramienta(tbTablaHerramienta);

        }

    }
    
    /**
     * Actualiza los datos de una herramienta electrónica existente
     */

    private void actualizar() {
        if (!validarCampos()) {
            return;
        }
        HerramientaElectronica herramienta = crearCamposherramienta();

        try {

            Map<String, Object> datos = crearMapeoDatosHerramienta(herramienta);
            Crud_HerramientaElectronica.actualizarHer_Elect("HerramientaElectronica", String.valueOf(herramienta.getId()), datos);
            JOptionPane.showMessageDialog(null, "Actualización con éxito");
            clearForm();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al Actualizar los datos de Herramientas");

        } finally {
            Crud_HerramientaElectronica.cargarTablaHerramienta(tbTablaHerramienta);

        }
    }

    /**
     * Elimina una herramienta electrónica de la base de datos
     */
    private void eliminar() {
        String idDoc = txtIngreso.getText();

        try {
            Crud_HerramientaElectronica.eliminarHer_Elect("HerramientaElectronica", idDoc);
            JOptionPane.showMessageDialog(null, "Eliminación con éxito");
            clearForm();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al Eliminar los datos de Herramientas");

        } finally {
            Crud_HerramientaElectronica.cargarTablaHerramienta(tbTablaHerramienta);

        }

    }
    
    /**
     * Limpia todos los campos del formulario
     */

    private void clearForm() {

        txtIngreso.setText("");
        txtNOmbre.setText("");
        txtPRecio.setText("");
        txtSTock.setText("");
        txtMArca.setText("");
        txtMOdelo.setText("");
        txtGArantia.setText("");
        jComboBox1.setSelectedIndex(0);
        txtVoltaje.setText("");
        txtFuente.setText("");

        ListBotonFuenteBateria.setSelectedItem("false");
        btEstuche.setSelectedItem("false");

        //txtFbateria.setText("");
        //txtEstuche.setText("");
        txtMaterial.setText("");
        txtAplic.setText("");
        txtCanpiezas.setText("");

    }
     /**
     * Busca una herramienta electrónica por su ID
     * Muestra los resultados en el formulario y tabla
     */
    

    private void busquedaID() {
        try {
            String idBusqueda = txtIngreso.getText().trim();
            if (idBusqueda.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese un ID de Búsqueda en el campo 'ID'");
                return;
            }

            HerramientaElectronica herramientaB = Crud_HerramientaElectronica.buscarHerramientaID(idBusqueda);

            if (herramientaB != null) {
                llenarCamposHerramienta(herramientaB);
                JOptionPane.showMessageDialog(null, "Herramienta Electrónica encontrada con Id: " + idBusqueda);
                mostrarEnTabla(herramientaB);
            } else {
                JOptionPane.showMessageDialog(null, "Herramienta Electrónica No encontrada");
                clearForm();
            }
        } catch (Exception e) {
            System.err.println("Error al buscar herramienta: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al buscar la herramienta");
        }
    }

    
    /**
     * Llena los campos del formulario con los datos de una herramienta
     * @param herramienta Objeto HerramientaElectronica con los datos a mostrar
     */
    
    private void llenarCamposHerramienta(HerramientaElectronica herramienta) {

        txtIngreso.setText(String.valueOf(herramienta.getId()));
        txtNOmbre.setText(herramienta.getNombre());
        txtPRecio.setText(String.valueOf(herramienta.getPrecio()));
        txtSTock.setText(String.valueOf(herramienta.getStock()));
        txtMArca.setText(herramienta.getMarca());
        txtMOdelo.setText(herramienta.getModelo());
        txtGArantia.setText(String.valueOf(herramienta.getGarantia()));
        String tipoHerramienta = herramienta.getTipoCategoria();
        jComboBox1.setSelectedItem(tipoHerramienta);
        txtFuente.setText(herramienta.getTipoFuenteEnergia());
        txtVoltaje.setText(String.valueOf(herramienta.getVoltaje()));

        ListBotonFuenteBateria.setSelectedItem(String.valueOf(herramienta.isFuenteDeBateria()));
        btEstuche.setSelectedItem(String.valueOf(herramienta.isIncluyeEstuche()));

        //txtFbateria.setText(String.valueOf(herramienta.isFuenteDeBateria()));
        //txtEstuche.setText(String.valueOf(herramienta.isIncluyeEstuche()));
        txtMaterial.setText(herramienta.getMaterial());
        txtAplic.setText(herramienta.getAplicacion());
        txtCanpiezas.setText(String.valueOf(herramienta.getCantidadPiezas()));

    }

    private void mostrarEnTabla(HerramientaElectronica herramienta) {
        // Obtener el modelo de la tabla
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tbTablaHerramienta.getModel();

        // Limpiar la tabla
        modelo.setRowCount(0);

        // Agregar la fila con los datos de la computadora
        Object[] fila = {
            herramienta.getId(),
            herramienta.getNombre(),
            herramienta.getPrecio(),
            herramienta.getStock(),
            herramienta.getMarca(),
            herramienta.getModelo(),
            herramienta.getGarantia(),
            jComboBox1.getSelectedItem().toString(),
            herramienta.getTipoFuenteEnergia(),
            herramienta.getVoltaje(),
            herramienta.isFuenteDeBateria(),
            herramienta.isIncluyeEstuche(),
            herramienta.getMaterial(),
            herramienta.getAplicacion(),
            herramienta.getCantidadPiezas()
        };

        modelo.addRow(fila);
    }

}
