package com.mycompany.proyecto_firebase;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 * La clase representa una herramienta electrónica como producto especializado.
 * Extendido de la clase Producto con atributos específicos de herramientas electrónicas.
 *
 * @author Marvin Batres
 */

public class Registro_Telefono extends javax.swing.JFrame {

   
    /**
     * Constructor que inicializa la interfaz y carga los datos de teléfonos.
     * Centra la ventana en la pantalla y carga la tabla inicial.
     */
    
    public Registro_Telefono() {
        initComponents();
        this.setLocationRelativeTo(null);
        Crud_Telefono.cargaTablaTelefono(tbTablaTelefono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTablaTelefono = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscarID = new javax.swing.JButton();
        btnLimpieza = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGarantia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAlmaGb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSistemaOp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTamanioPantalla = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTablaTelefono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTablaTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaTelefonoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTablaTelefono);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, 1062, 140));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setText("Registro");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 430, 159, 66));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 430, 159, 66));

        btnBuscarID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarID.setText("BusquedaID");
        btnBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIDActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 430, 159, 66));

        btnLimpieza.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpieza.setText("Limpieza");
        btnLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiezaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 430, 159, 66));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 159, 66));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 211, 36, -1));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 215, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 245, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 249, 182, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Precio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 283, -1, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 287, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Stock:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 321, 58, -1));
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 325, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Marca:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 353, -1, -1));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 357, 175, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Modelo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 211, -1, -1));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 215, 171, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Garantía:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 245, -1, -1));
        jPanel1.add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 249, 120, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Alamcenamiento GB:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 283, 182, -1));
        jPanel1.add(txtAlmaGb, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 287, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Ram GB:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 321, -1, -1));
        jPanel1.add(txtRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 325, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Sistema operativo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 353, -1, -1));
        jPanel1.add(txtSistemaOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 357, 100, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Registro Telefono");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 5, -1, 30));
        jPanel1.add(txtTamanioPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 213, 200, 26));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar Menu");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 190, 66));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tamaño Pantalla:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 211, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        guardar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu_Principal principal = new Menu_Principal();

        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tbTablaTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaTelefonoMouseClicked
        int seleccion = tbTablaTelefono.getSelectedRow();
        txtID.setText(tbTablaTelefono.getValueAt(seleccion, 0) + "");
        txtNombre.setText(tbTablaTelefono.getValueAt(seleccion, 1) + "");
        txtPrecio.setText(tbTablaTelefono.getValueAt(seleccion, 2) + "");
        txtStock.setText(tbTablaTelefono.getValueAt(seleccion, 3) + "");
        txtMarca.setText(tbTablaTelefono.getValueAt(seleccion, 4) + "");
        txtModelo.setText(tbTablaTelefono.getValueAt(seleccion, 5) + "");
        txtGarantia.setText(tbTablaTelefono.getValueAt(seleccion, 6) + "");
        txtAlmaGb.setText(tbTablaTelefono.getValueAt(seleccion, 7) + "");
        txtRam.setText(tbTablaTelefono.getValueAt(seleccion, 8) + "");
        txtSistemaOp.setText(tbTablaTelefono.getValueAt(seleccion, 9) + "");
        txtTamanioPantalla.setText(tbTablaTelefono.getValueAt(seleccion, 10) + "");
    }//GEN-LAST:event_tbTablaTelefonoMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiezaActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLimpiezaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIDActionPerformed
        BusquedaId();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Telefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Telefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Telefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Telefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Telefono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarID;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpieza;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTablaTelefono;
    private javax.swing.JTextField txtAlmaGb;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRam;
    private javax.swing.JTextField txtSistemaOp;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTamanioPantalla;
    // End of variables declaration//GEN-END:variables

    /**
     * Valida que los campos obligatorios del formulario estén completos.
     * Verifica que ID, Nombre, Precio, Stock y Marca no estén vacíos
     * y que los campos numéricos tengan formato válido.
     * 
     * @return true si todos los campos son válidos, false en caso contrario
     */
    
     private boolean validarCampos() {
        if (txtID.getText().trim().isEmpty()
                || txtNombre.getText().trim().isEmpty()
                || txtPrecio.getText().trim().isEmpty()
                || txtStock.getText().trim().isEmpty()
                   ||txtMarca.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor, Debe ingresar todos los campos obligatorios.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            Double.parseDouble(txtPrecio.getText().trim());
            Integer.parseInt(txtStock.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio y la cantidad deben ser valores numéricos.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    
    
    /**
     * Crea un objeto Telefono con los datos ingresados en el formulario.
     * @return Objeto Telefono con los datos del formulario
     */   
    
    private Telefono crearCamposTelefono() {
        return new Telefono(
                Integer.parseInt(txtID.getText()),
                txtNombre.getText(),
                Double.parseDouble(txtPrecio.getText()),
                Integer.parseInt(txtStock.getText()),
                txtMarca.getText(),
                txtModelo.getText(),
                Double.parseDouble(txtGarantia.getText()),
                Integer.parseInt(txtAlmaGb.getText()),
                Integer.parseInt(txtRam.getText()),
                txtSistemaOp.getText(),
                txtTamanioPantalla.getText()
        );

    }

    private Map<String, Object> crearMapeoDatosTelefono(Telefono telefono) {
        Map<String, Object> datos = new HashMap();

        datos.put("Nombre", telefono.getNombre());
        datos.put("Precio", telefono.getPrecio());
        datos.put("Stock", telefono.getStock());
        datos.put("Marca", telefono.getMarca());
        datos.put("Modelo", telefono.getModelo());
        datos.put("Garantia", telefono.getGarantia());
        datos.put("AlmacenamientoGB", telefono.getAlmacenamientoGB());
        datos.put("CapacdidadRam", telefono.getCapacidadRam());
        datos.put("soOperativo", telefono.getSoOperativo());
        datos.put("Tamaño", telefono.getTamanio());

        return datos;
    }
    
    
       /**
     * Guarda un nuevo teléfono en la base de datos Firebase.
     * Valida los campos, crea el objeto y lo almacena en la colección "Telefono".
     * Actualiza la tabla del formulario después de guardar.
     */
    

    private void guardar() {
        if (!validarCampos()) {
            return;
        }
        Telefono telefono = crearCamposTelefono();

        try {
            Map<String, Object> datos = crearMapeoDatosTelefono(telefono);
            Crud_Telefono.guardarTelefono("Telefono", String.valueOf(telefono.getId()), datos);
            JOptionPane.showMessageDialog(null, "Telefono guardado con exito en Firebase. ");
            clearForm();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al guardar");

        } finally {
            Crud_Telefono.cargaTablaTelefono(tbTablaTelefono);

        }

    }
    
    /**
     * Actualiza los datos de un teléfono existente en Firebase.
     * Utiliza el ID del teléfono para localizar y actualizar el registro.
     * Actualiza la tabla después de modificar.
     */
    private void actualizar() {
        if (!validarCampos()) {
            return;
        }
        Telefono telefono = crearCamposTelefono();

        try {
            Map<String, Object> datos = crearMapeoDatosTelefono(telefono);
            Crud_Telefono.actualizarTelefono("Telefono", String.valueOf(telefono.getId()), datos);
            JOptionPane.showMessageDialog(null, "Telefono Actualizado con exito en Firebase. ");
            clearForm();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al guardar");

        } finally {
            Crud_Telefono.cargaTablaTelefono(tbTablaTelefono);

        }

    }
    
    /**
     * Elimina un teléfono de la base de datos Firebase.
     * Utiliza el ID del teléfono para localizar y eliminar el registro.
     * Actualiza la tabla después de eliminar.
     */

    private void eliminar() {
        String idDoc = txtID.getText();
        try {
            Crud_computadora.eliminarComputadora("Telefono", idDoc);
            JOptionPane.showMessageDialog(null, "Eliminación de los datos de telefono con éxito");
            clearForm();

        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al Eliminar los datos Telefono");

        } finally {
            Crud_Telefono.cargaTablaTelefono(tbTablaTelefono);

        }

    }
    
    /**
     * Busca un teléfono por su ID en la base de datos.
     * Muestra los resultados en el formulario y en la tabla.
     * Si no encuentra el teléfono, muestra un mensaje de error.
     */

    private void clearForm() {

        txtID.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtGarantia.setText("");
        txtAlmaGb.setText("");
        txtRam.setText("");
        txtSistemaOp.setText("");
        txtTamanioPantalla.setText("");

    }
    
    
    /**
     * Busca un teléfono por su ID en la base de datos.
     * Muestra los resultados en el formulario y en la tabla.
     * Si no encuentra el teléfono, muestra un mensaje de error.
     */ 

    private void BusquedaId() {
        try {
            String idBusqueda = txtID.getText().trim();

            if (idBusqueda.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese un ID de Busqueda en el campo 'ID'");
                return;
            }

            Telefono telefonoB = Crud_Telefono.buscarTelefonoID(idBusqueda);

            if (telefonoB != null) {
                llenarCamposTelefono(telefonoB);
                JOptionPane.showMessageDialog(null, "Telefono encontrada con Id: " + idBusqueda);
                mostrarEnTabla(telefonoB);
            } else {

                JOptionPane.showMessageDialog(null, "Telefono No encontrada ");
                clearForm();

            }

        } catch (Exception e) {
            System.err.println("Error al buscar computadora: " + e.getMessage());

        }
    }
    
    
     /**
     * Llena los campos del formulario con los datos de un objeto Telefono.
     * @param telefono Objeto Telefono con los datos a mostrar
     */

    private void llenarCamposTelefono(Telefono telefono) {

        txtID.setText(String.valueOf(telefono.getId()));
        txtNombre.setText(telefono.getNombre());
        txtPrecio.setText(String.valueOf(telefono.getPrecio()));
        txtStock.setText(String.valueOf(telefono.getStock()));
        txtMarca.setText(telefono.getMarca());
        txtModelo.setText(telefono.getModelo());
        txtGarantia.setText(String.valueOf(telefono.getGarantia()));
        txtAlmaGb.setText(String.valueOf(telefono.getAlmacenamientoGB()));
        txtRam.setText(String.valueOf(telefono.getCapacidadRam()));
        txtSistemaOp.setText(telefono.getSoOperativo());
        txtTamanioPantalla.setText(telefono.getTamanio());

    }

    private void mostrarEnTabla(Telefono telefono) {

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tbTablaTelefono.getModel();

        modelo.setRowCount(0);
        
        Object[] fila = {

            telefono.getId(),
            telefono.getNombre(),
            telefono.getPrecio(),
            telefono.getStock(),
            telefono.getMarca(),
            telefono.getModelo(),
            telefono.getGarantia(),
            telefono.getAlmacenamientoGB(),
            telefono.getCapacidadRam(),
            telefono.getSoOperativo(),
            telefono.getTamanio(),
            };   
        modelo.addRow (fila);
    }

}
