/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_firebase;


import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class Registro_AsistenteCasa extends javax.swing.JFrame {

    /**
     * Creates new form Registro_AsistenteCasa
     */
    public Registro_AsistenteCasa() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGarantia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTipoDispositivo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProtComunicacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCompAsistente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPantalla = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEnt_Sal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtInalambrico = new javax.swing.JTextField();
        txtRangoConexion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHub = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 701, 195));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 495, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 207, 37, 30));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 214, 103, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 243, 86, 30));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 103, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Precio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 279, -1, 30));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 286, 103, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Stock:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 315, -1, 30));
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 322, 103, -1));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 358, 103, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Marca:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 351, 61, 30));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 394, 103, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Modelo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 387, 97, 30));
        jPanel1.add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 430, 109, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Garantia:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 423, 97, 30));
        jPanel1.add(txtTipoDispositivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 214, 113, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("TipoDisp:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Prot. Comunicación:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 246, -1, -1));
        jPanel1.add(txtProtComunicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 250, 99, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Comp. Asistente:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 282, -1, -1));
        jPanel1.add(txtCompAsistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 286, 117, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Tiene Pantalla:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 318, 153, -1));
        jPanel1.add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 322, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tipo de E/S:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 354, 141, -1));
        jPanel1.add(txtEnt_Sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 358, 104, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("esInalambrico:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 390, 153, -1));
        jPanel1.add(txtInalambrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 394, 120, -1));
        jPanel1.add(txtRangoConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 430, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Rango Conexión:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 426, 153, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Hub:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 459, 48, 30));
        jPanel1.add(txtHub, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 466, 109, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("Actualizar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 495, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setText("BusquedaID");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 495, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton4.setText("Limpiar");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 495, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton5.setText("Eliminar");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 495, -1, -1));

        jButton6.setText("Regresar menu principal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 530, 191, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu_Principal principal = new Menu_Principal();

        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_AsistenteCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_AsistenteCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_AsistenteCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_AsistenteCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_AsistenteCasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCompAsistente;
    private javax.swing.JTextField txtEnt_Sal;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtHub;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtInalambrico;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProtComunicacion;
    private javax.swing.JTextField txtRangoConexion;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTipoDispositivo;
    // End of variables declaration//GEN-END:variables

    
    private AsistenteCasa crearAsistente(){
        
        return new AsistenteCasa(
                
                Integer.parseInt(txtID.getText()),
                txtNombre.getText(),
                Double.parseDouble(txtPrecio.getText()),
                Integer.parseInt(txtStock.getText()),
                txtMarca.getText(),
                txtModelo.getText(),
                Integer.parseInt(txtGarantia.getText()),
                txtTipoDispositivo.getText(),
                txtProtComunicacion.getText(),
                txtCompAsistente.getText(),
                Boolean.parseBoolean(txtPantalla.getText()),
                txtEnt_Sal.getText(),
                Boolean.parseBoolean(txtInalambrico.getText()),
                txtRangoConexion.getText(),
                Boolean.parseBoolean(txtHub.getText())
        );
        
    }
    
   private Map<String, Object> crearMapeoDatosAsistCasa(AsistenteCasa asistentecasa){
       Map<String, Object> datos = new HashMap();
       
       datos.put("Nombre",asistentecasa.getNombre());
       datos.put("Precio",asistentecasa.getPrecio());
       datos.put("stock",asistentecasa.getStock());
       datos.put("Marca",asistentecasa.getMarca());
       datos.put("Modelo",asistentecasa.getModelo());
       datos.put("Garantía",asistentecasa.getGarantia());
       datos.put("TipoDispositivo",asistentecasa.getTipoDispositivo());
       datos.put("protocoloComunicacion",asistentecasa.getProtocoloComunicacion());
       datos.put("TienePantalla",asistentecasa.isTienePantalla());
       datos.put("EntradaSalida",asistentecasa.getEntradasSalidas());
       datos.put("esInalambrico",asistentecasa.isEsInalambrico());
       datos.put("RangoConexion",asistentecasa.getRangoConexion());
       datos.put("RequiereHub",asistentecasa.isRequiereHub());
       
       return datos;
   } 
    
    
    private void guardar() {
        AsistenteCasa ia = crearAsistente();
        try{
            Map<String, Object> datos = crearMapeoDatosAsistCasa(ia);
            Crud_AsistenteCasa.guardarAsistenteCasa("AsistenteCasa", String.valueOf(ia.getId()), datos);
           JOptionPane.showMessageDialog(null, "Guardado de datos con exito");
           
        }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Error al guarda los datos.");
            System.err.println("Error al introducir los datos");
        }
        
    
    }
}
